version: '2'

services:
        web:
                build: .
                ports:
                        - '10019:80'
                stdin_open: true
                tty: true
                volumes:
                        - ./logs:/var/log/apache2
                        - ./source:/var/www/html
                        - ./php.ini:/etc/php/7.0/apache2/php.ini
                        - ./flag:/flag.txt
